from flask import Flask, render_template, request, redirect, url_for, jsonify, Response, flash, session
from models import db, Material, MaterialVariant, Supplier, UsageLog, Sale, SaleItem, ReorderRequest
from utils import get_low_stock, predict_depletion_days
from flask_migrate import Migrate
from datetime import datetime
import smtplib
from email.mime.text import MIMEText
import os


def to_float(value):
    try:
        return float(value)
    except (TypeError, ValueError):
        return 0.0

# ---------------- EMAIL FUNCTION ----------------


def send_order_email(material, supplier, qty):
    try:
        if not supplier or not supplier.contact:
            return

        message = f"""
Order Request

Material: {material.name}
Quantity: {qty} {material.unit}

Supplier: {supplier.name}

Please confirm availability.

Generated by Construction Inventory System.
"""
        msg = MIMEText(message)
        msg["Subject"] = "Material Order Request"
        msg["From"] = "your_email@gmail.com"
        msg["To"] = supplier.contact

        server = smtplib.SMTP("smtp.gmail.com", 587)
        server.starttls()
        server.login("your_email@gmail.com", "your_app_password")
        server.send_message(msg)
        server.quit()

    except Exception as e:
        print("Email failed:", e)

# ---------------- CREATE APP ----------------


def create_app():
    app = Flask(__name__, instance_relative_config=True)

    # Ensure instance folder exists
    os.makedirs(app.instance_path, exist_ok=True)

    # Database config
    app.config['SQLALCHEMY_DATABASE_URI'] = 'sqlite:///' + \
        os.path.join(app.instance_path, 'inventory.db')
    app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = False
    app.config['SECRET_KEY'] = 'inventory-secret'

    db.init_app(app)
    Migrate(app, db)

    # ---------------- ROUTES ----------------
    @app.route('/')
    def index():
        materials = Material.query.order_by(Material.name).all()
        return render_template('index.html', materials=materials, low_count=len(get_low_stock()))

    @app.route('/inventory')
    def inventory():
        materials = Material.query.order_by(Material.name).all()
        return render_template('inventory.html', materials=materials, low_count=len(get_low_stock()))

    @app.route('/materials/add', methods=['GET', 'POST'])
    def add_material():
        suppliers = Supplier.query.order_by(Supplier.name).all()
        categories = [
            "Bits & Disc", "Hand Tools", "Concreting & Masonry",
            "Nail, Tox, & Screws", "Wood Products",
            "Rebars & G.I Wires", "Drywall & Ceiling"
        ]

        if request.method == 'POST':
            price_value = request.form.get(
                'price') or request.form.get('price_per_unit') or 0
            new_material = Material(
                name=request.form['name'],
                category=request.form.get('category'),
                quantity=to_float(request.form.get('quantity')),
                unit=request.form.get('unit', 'pcs'),
                reorder_point=to_float(request.form.get('reorder_point')),
                supplier_id=request.form.get('supplier_id') or None,
                price_per_unit=float(price_value)
            )
            db.session.add(new_material)
            db.session.commit()

            variant_names = request.form.getlist('variant_name[]')
            variant_quantities = request.form.getlist('variant_quantity[]')
            variant_units = request.form.getlist('variant_unit[]')
            variant_prices = request.form.getlist('variant_price[]')

            for i, name in enumerate(variant_names):
                if name.strip() == '':
                    continue
                variant = MaterialVariant(
                    material_id=new_material.id,
                    name=name.strip(),
                    quantity=to_float(variant_quantities[i]),
                    unit=variant_units[i] or 'pcs',
                    price=to_float(variant_prices[i])
                )
                db.session.add(variant)
            db.session.commit()

            return redirect(url_for('inventory'))

        return render_template('add_edit_material.html', suppliers=suppliers, categories=categories, material=None, low_count=len(get_low_stock()))

    @app.route('/materials/<int:id>/edit', methods=['GET', 'POST'])
    def edit_material(id):
        material = Material.query.get_or_404(id)
        suppliers = Supplier.query.order_by(Supplier.name).all()
        categories = [
            "Bits & Disc", "Hand Tools", "Concreting & Masonry",
            "Nail, Tox, & Screws", "Wood Products",
            "Rebars & G.I Wires", "Drywall & Ceiling"
        ]

        if request.method == 'POST':
            material.name = request.form['name']
            material.category = request.form.get('category')
            material.quantity = to_float(request.form.get('quantity'))
            material.unit = request.form.get('unit', material.unit)
            material.reorder_point = float(
                request.form.get('reorder_point', 0))
            material.supplier_id = request.form.get('supplier_id') or None

            price_value = request.form.get(
                'price') or request.form.get('price_per_unit')
            material.price_per_unit = float(
                price_value) if price_value else 0.0

            db.session.commit()

            for v in material.variants:
                db.session.delete(v)
            db.session.commit()

            variant_names = request.form.getlist('variant_name[]')
            variant_quantities = request.form.getlist('variant_quantity[]')
            variant_units = request.form.getlist('variant_unit[]')
            variant_prices = request.form.getlist('variant_price[]')

            for i, name in enumerate(variant_names):
                if name.strip() == '':
                    continue
                variant = MaterialVariant(
                    material_id=material.id,
                    name=name.strip(),
                    quantity=to_float(variant_quantities[i]),
                    unit=variant_units[i] or 'pcs',
                    price=to_float(variant_prices[i])
                )
                db.session.add(variant)
            db.session.commit()

            return redirect(url_for('inventory'))

        return render_template('add_edit_material.html', material=material, suppliers=suppliers, categories=categories, low_count=len(get_low_stock()))

    @app.route('/materials/<int:id>/delete', methods=['POST'])
    def delete_material(id):
        material = Material.query.get_or_404(id)
        db.session.delete(material)
        db.session.commit()
        return redirect(url_for('inventory'))

    @app.route('/materials/<int:material_id>/reorder', methods=['GET', 'POST'])
    def reorder(material_id):
        material = Material.query.get_or_404(material_id)
        suppliers = Supplier.query.all()
        if request.method == 'POST':
            reorder_qty = float(request.form.get('reorder_qty', 0))
            if reorder_qty <= 0:
                return render_template('reorder.html', material=material, suppliers=suppliers, error="Enter valid quantity.", low_count=len(get_low_stock()))

            supplier = Supplier.query.get(
                material.supplier_id) if material.supplier_id else None
            send_order_email(material, supplier, reorder_qty)

            reorder_request = ReorderRequest(
                material_id=material.id, supplier_id=supplier.id if supplier else None, requested_qty=reorder_qty, status="Pending")
            db.session.add(reorder_request)

            if not material.variants:
                material.quantity += reorder_qty

            db.session.commit()
            return redirect(url_for('inventory'))

        return render_template('reorder.html', material=material, suppliers=suppliers, low_count=len(get_low_stock()))

    @app.route('/suppliers', methods=['GET', 'POST'])
    def suppliers_view():
        if request.method == 'POST':
            s = Supplier(
                name=request.form['name'],
                contact=request.form.get('contact'),
                address=request.form.get('address')
            )
            db.session.add(s)
            db.session.commit()
            return redirect(url_for('suppliers_view'))

        suppliers = Supplier.query.order_by(Supplier.name).all()
        return render_template('suppliers.html', suppliers=suppliers, low_count=len(get_low_stock()))

    @app.route('/supplier/edit/<int:id>', methods=['GET', 'POST'])
    def edit_supplier(id):
        supplier = Supplier.query.get_or_404(id)
        if request.method == 'POST':
            supplier.name = request.form.get('name')
            supplier.contact = request.form.get('contact')
            supplier.address = request.form.get('address')
            db.session.commit()
            flash("Supplier updated successfully", "success")
            return redirect(url_for('suppliers_view'))
        return render_template('edit_supplier.html', supplier=supplier)

    @app.route('/reorder/update/<int:id>', methods=['POST'])
    def update_reorder_status(id):
        reorder = ReorderRequest.query.get_or_404(id)
        new_status = request.form.get('status')
        reorder.status = new_status

        if new_status == "Received":
            material = Material.query.get(reorder.material_id)
            sale = Sale(date=datetime.utcnow(), type="restock")
            db.session.add(sale)
            db.session.flush()

            sale_item = SaleItem(
                sale_id=sale.id,
                material_id=material.id,
                qty=reorder.requested_qty,
                price=material.price_per_unit or 0
            )
            db.session.add(sale_item)
            sale.total = reorder.requested_qty * (material.price_per_unit or 0)
            material.quantity += reorder.requested_qty
            db.session.delete(reorder)

        db.session.commit()
        return redirect(url_for('notifications'))

    @app.route('/sales')
    def sales():
        all_sales = Sale.query.order_by(Sale.date.desc()).all()
        sales = [s for s in all_sales if s.type == "sale"]
        restocks = [s for s in all_sales if s.type == "restock"]
        return render_template('sales.html', sales=sales, restocks=restocks, low_count=len(get_low_stock()))

    @app.route('/sales/export')
    def sales_export():
        sales = Sale.query.order_by(Sale.date.desc()).all()

        def generate():
            yield "Date,Material,Quantity,Price,Total\n"
            for sale in sales:
                for item in sale.items:
                    yield f"{sale.date},{item.material.name},{item.qty},{item.price},{sale.total}\n"
        return Response(generate(), mimetype="text/csv", headers={"Content-Disposition": "attachment;filename=sales_report.csv"})

    @app.route('/sales/clear', methods=['POST'])
    def clear_sales():
        SaleItem.query.delete()
        Sale.query.delete()
        db.session.commit()
        flash("All sales records have been cleared.", "success")
        return redirect(url_for('sales'))

    @app.route("/checkout", methods=["POST"])
    def checkout():
        data = request.get_json(silent=True) or {}
        cart = data.get("cart", [])
        if not cart:
            return jsonify({"success": False})

        sale = Sale(date=datetime.utcnow())
        db.session.add(sale)
        total_amount = 0.0

        for item in cart:
            material_id = int(item.get("id"))
            qty = float(item.get("qty", 0))
            price = float(item.get("price", 0))
            variant_name = item.get("variant")
            material = db.session.get(Material, material_id)

            if variant_name:
                variant = MaterialVariant.query.filter_by(
                    material_id=material_id, name=variant_name).first()
                if not variant or variant.quantity < qty:
                    return jsonify({"success": False})
                variant.quantity -= qty
            else:
                if material.quantity < qty:
                    return jsonify({"success": False})
                material.quantity -= qty

            sale_item = SaleItem(
                sale_id=sale.id, material_id=material.id, qty=qty, price=price)
            db.session.add(sale_item)
            total_amount += qty * price

        sale.total = total_amount
        db.session.commit()
        return jsonify({"success": True})

    @app.route('/supplier/delete/<int:id>', methods=['POST'])
    def delete_supplier(id):
        supplier = Supplier.query.get_or_404(id)
        db.session.delete(supplier)
        db.session.commit()
        flash(f"Supplier '{supplier.name}' has been deleted.", "success")
        return redirect(url_for('suppliers_view'))

    @app.route('/notifications')
    def notifications():
        dismissed = session.get('dismissed_notifications', [])
        low_materials = get_low_stock(exclude_ids=dismissed)
        for m in low_materials:
            m.pred_days = predict_depletion_days(m)
        return render_template('notifications.html', low=low_materials, low_count=len(low_materials))

    @app.route('/notifications/dismiss/<int:material_id>')
    def dismiss_notification(material_id):
        material = Material.query.get(material_id)
        if not material:
            flash('Notification target material not found.', 'warning')
            return redirect(url_for('notifications'))

        dismissed = session.get('dismissed_notifications', [])
        if material_id not in dismissed:
            dismissed.append(material_id)
            session['dismissed_notifications'] = dismissed

        flash(f"Notification for '{material.name}' dismissed.", 'success')
        return redirect(url_for('notifications'))

    @app.route('/settings')
    def settings():
        return render_template('settings.html', low_count=len(get_low_stock()))

    @app.route('/about')
    def about():
        return render_template('about.html', low_count=len(get_low_stock()))

    return app


# ---------------- RUN APP ----------------
app = create_app()

if __name__ == '__main__':
    print("Running app on http://127.0.0.1:5000/")
    app.run(debug=True, host='127.0.0.1', port=5000)
