"""Fix price saving and sale checkout

Revision ID: 436b9a6c4485
Revises: 66a9e1c58217
Create Date: 2025-11-03 00:42:29.463851

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '436b9a6c4485'
down_revision = '66a9e1c58217'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('material', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price_per_unit', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('subtotal', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('material', schema=None) as batch_op:
        batch_op.drop_column('subtotal')
        batch_op.drop_column('price_per_unit')

    # ### end Alembic commands ###
