"""Add some_new_column

Revision ID: 5cbb9dcde267
Revises: e00e4944d207
Create Date: 2026-03-31 22:50:14.843617

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5cbb9dcde267'
down_revision = 'e00e4944d207'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - adjusted for SQLite ###

    with op.batch_alter_table('material', schema=None) as batch_op:
        batch_op.alter_column(
            'quantity',
            existing_type=sa.INTEGER(),
            type_=sa.Float(),
            existing_nullable=True
        )
        batch_op.alter_column(
            'reorder_point',
            existing_type=sa.REAL(),
            type_=sa.Float(),
            existing_nullable=True,
            existing_server_default=sa.text('0')
        )
        # give the foreign key constraint a proper name
        batch_op.create_foreign_key(
            'fk_material_supplier_id',  # <-- constraint name
            'supplier',
            ['supplier_id'],
            ['id']
        )


def downgrade():
    with op.batch_alter_table('material', schema=None) as batch_op:
        # drop the foreign key using its name
        batch_op.drop_constraint('fk_material_supplier_id', type_='foreignkey')
        batch_op.alter_column(
            'reorder_point',
            existing_type=sa.Float(),
            type_=sa.REAL(),
            existing_nullable=True,
            existing_server_default=sa.text('0')
        )
        batch_op.alter_column(
            'quantity',
            existing_type=sa.Float(),
            type_=sa.INTEGER(),
            existing_nullable=True
        )
