"""Add price_per_unit column to Material

Revision ID: 66a9e1c58217
Revises: 
Create Date: 2025-11-03 00:24:54.424445

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66a9e1c58217'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('material', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price', sa.Float(), nullable=True))
        batch_op.drop_column('price_per_unit')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('material', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price_per_unit', sa.FLOAT(), nullable=True))
        batch_op.drop_column('price')

    # ### end Alembic commands ###
